### ISSUE TITLE
Uncaught ReferenceError: wrapper is not defined

### ISSUE THREAD

**Issue by Zorono** [lleblanc42/bootstrap-FileUpload#24]
Exception: `Uncaught ReferenceError: wrapper is not defined` (Line 99 `instance[el].wrapper.append(instance[el].filePreviewTable);`)
Code: 
    `
     <div class="fileupload-wrapper"><div id="MultiPart-Upload"></div></div>
     <script type="text/javascript>
        $("#MultiPart-Upload").bootstrapFileUpload({
           url: "upload.php",
           debug: true
        });
     </script>
   `

**Comment by lleblanc42** [comment]
To fix this issue, please add instance[el]. before wrapper on line 628 in bootstrap-FileUpload.js. I will get this patched in dev, but need to finish up what I was working on and test it before I push it to master. Sorry for the inconvenience and thank you for bringing the bug to light. I also noticed a bug with checking for font awesome as well. It doesn't detect use of CDN.
