### ISSUE TITLE
Add the ability to send/receive File data in basic url.

### ISSUE THREAD

**Issue by Zorono** [lleblanc42/bootstrap-FileUpload#30]
Hello @lleblanc42 , it 'd be great if added the ability to send/receive File data in basic url.
for example: http://php.net/manual/en/features.file-upload.post-method.php

**Comment by lleblanc42** [comment]
Please elaborate. Currently, the plugin sends the data as POST data via ajax to wherever the url is set to. It's basically like using an HTML form except the screen doesn't redraw.
